

module Latte.Parser.Abs where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Program a = Program a [TopDef a]
  deriving (Eq, Ord, Show, Read)

instance Functor Program where
    fmap f x = case x of
        Program a topdefs -> Program (f a) (map (fmap f) topdefs)
data TopDef a = FnDef a (Fn a) | ClsDef a (ClsHeader a) [ClsElem a]
  deriving (Eq, Ord, Show, Read)

instance Functor TopDef where
    fmap f x = case x of
        FnDef a fn -> FnDef (f a) (fmap f fn)
        ClsDef a clsheader clselems -> ClsDef (f a) (fmap f clsheader) (map (fmap f) clselems)
data Fn a = Fn a (Type a) Ident [Arg a] (Block a)
  deriving (Eq, Ord, Show, Read)

instance Functor Fn where
    fmap f x = case x of
        Fn a type_ ident args block -> Fn (f a) (fmap f type_) ident (map (fmap f) args) (fmap f block)
data ClsHeader a = BaseCls a Ident | SubCls a Ident Ident
  deriving (Eq, Ord, Show, Read)

instance Functor ClsHeader where
    fmap f x = case x of
        BaseCls a ident -> BaseCls (f a) ident
        SubCls a ident1 ident2 -> SubCls (f a) ident1 ident2
data ClsElem a = Method a (Fn a) | Field a (Type a) Ident
  deriving (Eq, Ord, Show, Read)

instance Functor ClsElem where
    fmap f x = case x of
        Method a fn -> Method (f a) (fmap f fn)
        Field a type_ ident -> Field (f a) (fmap f type_) ident
data Arg a = Arg a (Type a) Ident
  deriving (Eq, Ord, Show, Read)

instance Functor Arg where
    fmap f x = case x of
        Arg a type_ ident -> Arg (f a) (fmap f type_) ident
data Block a = Block a [Stmt a]
  deriving (Eq, Ord, Show, Read)

instance Functor Block where
    fmap f x = case x of
        Block a stmts -> Block (f a) (map (fmap f) stmts)
data Stmt a
    = Empty a
    | BStmt a (Block a)
    | Decl a (Type a) [Item a]
    | Ass a Ident (Expr a)
    | Incr a Ident
    | Decr a Ident
    | Ret a (Expr a)
    | VRet a
    | Cond a (Expr a) (Stmt a)
    | CondElse a (Expr a) (Stmt a) (Stmt a)
    | While a (Expr a) (Stmt a)
    | ForEach a (Type a) Ident Ident (Stmt a)
    | SExp a (Expr a)
  deriving (Eq, Ord, Show, Read)

instance Functor Stmt where
    fmap f x = case x of
        Empty a -> Empty (f a)
        BStmt a block -> BStmt (f a) (fmap f block)
        Decl a type_ items -> Decl (f a) (fmap f type_) (map (fmap f) items)
        Ass a ident expr -> Ass (f a) ident (fmap f expr)
        Incr a ident -> Incr (f a) ident
        Decr a ident -> Decr (f a) ident
        Ret a expr -> Ret (f a) (fmap f expr)
        VRet a -> VRet (f a)
        Cond a expr stmt -> Cond (f a) (fmap f expr) (fmap f stmt)
        CondElse a expr stmt1 stmt2 -> CondElse (f a) (fmap f expr) (fmap f stmt1) (fmap f stmt2)
        While a expr stmt -> While (f a) (fmap f expr) (fmap f stmt)
        ForEach a type_ ident1 ident2 stmt -> ForEach (f a) (fmap f type_) ident1 ident2 (fmap f stmt)
        SExp a expr -> SExp (f a) (fmap f expr)
data Item a = NoInit a Ident | Init a Ident (Expr a)
  deriving (Eq, Ord, Show, Read)

instance Functor Item where
    fmap f x = case x of
        NoInit a ident -> NoInit (f a) ident
        Init a ident expr -> Init (f a) ident (fmap f expr)
data BasicType a = TInt a | TStr a | TBool a
  deriving (Eq, Ord, Show, Read)

instance Functor BasicType where
    fmap f x = case x of
        TInt a -> TInt (f a)
        TStr a -> TStr (f a)
        TBool a -> TBool (f a)
data Type a
    = TVoid a
    | TArr a (Type a)
    | TBasic a (BasicType a)
    | TObj a Ident
    | Fun a (Type a) [Type a]
  deriving (Eq, Ord, Show, Read)

instance Functor Type where
    fmap f x = case x of
        TVoid a -> TVoid (f a)
        TArr a type_ -> TArr (f a) (fmap f type_)
        TBasic a basictype -> TBasic (f a) (fmap f basictype)
        TObj a ident -> TObj (f a) ident
        Fun a type_ types -> Fun (f a) (fmap f type_) (map (fmap f) types)
data Expr a
    = EVar a Ident
    | ELitInt a Integer
    | ELitTrue a
    | ELitFalse a
    | ENewArr a (BasicType a) (Expr a)
    | ENewObj a Ident
    | ENewObjConstructor a Ident [Expr a]
    | EApp a Ident [Expr a]
    | EArr a Ident (Expr a)
    | EString a String
    | ENeg a (Expr a)
    | ENot a (Expr a)
    | EMul a (Expr a) (MulOp a) (Expr a)
    | EAdd a (Expr a) (AddOp a) (Expr a)
    | ERel a (Expr a) (RelOp a) (Expr a)
    | EAnd a (Expr a) (Expr a)
    | EOr a (Expr a) (Expr a)
  deriving (Eq, Ord, Show, Read)

instance Functor Expr where
    fmap f x = case x of
        EVar a ident -> EVar (f a) ident
        ELitInt a integer -> ELitInt (f a) integer
        ELitTrue a -> ELitTrue (f a)
        ELitFalse a -> ELitFalse (f a)
        ENewArr a basictype expr -> ENewArr (f a) (fmap f basictype) (fmap f expr)
        ENewObj a ident -> ENewObj (f a) ident
        ENewObjConstructor a ident exprs -> ENewObjConstructor (f a) ident (map (fmap f) exprs)
        EApp a ident exprs -> EApp (f a) ident (map (fmap f) exprs)
        EArr a ident expr -> EArr (f a) ident (fmap f expr)
        EString a string -> EString (f a) string
        ENeg a expr -> ENeg (f a) (fmap f expr)
        ENot a expr -> ENot (f a) (fmap f expr)
        EMul a expr1 mulop expr2 -> EMul (f a) (fmap f expr1) (fmap f mulop) (fmap f expr2)
        EAdd a expr1 addop expr2 -> EAdd (f a) (fmap f expr1) (fmap f addop) (fmap f expr2)
        ERel a expr1 relop expr2 -> ERel (f a) (fmap f expr1) (fmap f relop) (fmap f expr2)
        EAnd a expr1 expr2 -> EAnd (f a) (fmap f expr1) (fmap f expr2)
        EOr a expr1 expr2 -> EOr (f a) (fmap f expr1) (fmap f expr2)
data AddOp a = Plus a | Minus a
  deriving (Eq, Ord, Show, Read)

instance Functor AddOp where
    fmap f x = case x of
        Plus a -> Plus (f a)
        Minus a -> Minus (f a)
data MulOp a = Times a | Div a | Mod a
  deriving (Eq, Ord, Show, Read)

instance Functor MulOp where
    fmap f x = case x of
        Times a -> Times (f a)
        Div a -> Div (f a)
        Mod a -> Mod (f a)
data RelOp a = LTH a | LE a | GTH a | GE a | EQU a | NE a
  deriving (Eq, Ord, Show, Read)

instance Functor RelOp where
    fmap f x = case x of
        LTH a -> LTH (f a)
        LE a -> LE (f a)
        GTH a -> GTH (f a)
        GE a -> GE (f a)
        EQU a -> EQU (f a)
        NE a -> NE (f a)
