-- automatically generated by BNF Converter
module Latte.Parser.Test where


import System.IO ( stdin, hGetContents )
import System.Environment ( getArgs, getProgName )
import System.Exit ( exitFailure, exitSuccess )
import Control.Monad (when)

import Latte.Parser.Lex
import Latte.Parser.Par
import Latte.Parser.Skel
import Latte.Parser.Print
import Latte.Parser.Abs




import Latte.Parser.ErrM

type ParseFun a = [Token] -> Err a

myLLexer = myLexer

type Verbosity = Int

run :: (Print a, Show a) => Verbosity -> ParseFun a -> String -> Err a
run v p s = let ts = myLLexer s in p ts



